### ISSUE TITLE
Can we implement a diagonal MvNormal distribution and its manifold

### ISSUE THREAD

**Issue by bvdmitri** [ReactiveBayes/ExponentialFamilyManifolds.jl#8]
This option significantly reduces computational requirements for large `MvNormal` (at a cost of accuracy of course). This will up to a user if they want to project on a full MvNormal or an MvNormal constraint to have a diagonal covariance matrix.

**Comment by Nimrais** [comment]
Yes we can, but first we need to implement an exponential family member for it https://github.com/ReactiveBayes/ExponentialFamily.jl/issues/201.

**Comment by Nimrais** [comment]
done here https://github.com/ReactiveBayes/ExponentialFamilyManifolds.jl/pull/22
